# Generated by Django 4.2.20 on 2025-05-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_user_slot_booking',
        ),
    ]
