# Generated by Django 4.2.20 on 2025-05-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_unique_user_slot_booking'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='availableslot',
            name='unique_slot',
        ),
    ]
