# Generated by Django 4.2.20 on 2025-05-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
