# Generated by Django 4.2.20 on 2025-05-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_availableslot_unique_slot'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='availableslot',
            constraint=models.UniqueConstraint(fields=('date', 'time', 'location'), name='unique_slot'),
        ),
    ]
